// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjmg9jlqHBpjlwjZKG-D7UaT5QrXIIJEY',
    appId: '1:138198515903:web:67322f6de5a91d9426060a',
    messagingSenderId: '138198515903',
    projectId: 'tp1-firebase-28924',
    authDomain: 'tp1-firebase-28924.firebaseapp.com',
    databaseURL: 'https://tp1-firebase-28924-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tp1-firebase-28924.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX2FafJOhDWuhpVlYnP5KCxfKsBbIhjZk',
    appId: '1:138198515903:android:a4da3c9d03521bca26060a',
    messagingSenderId: '138198515903',
    projectId: 'tp1-firebase-28924',
    databaseURL: 'https://tp1-firebase-28924-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tp1-firebase-28924.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJnjmsoRsEUfUXc-E_fQAKoZJmmkMWJCE',
    appId: '1:138198515903:ios:77300db5737d597526060a',
    messagingSenderId: '138198515903',
    projectId: 'tp1-firebase-28924',
    databaseURL: 'https://tp1-firebase-28924-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tp1-firebase-28924.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJnjmsoRsEUfUXc-E_fQAKoZJmmkMWJCE',
    appId: '1:138198515903:ios:25371168470a7bc926060a',
    messagingSenderId: '138198515903',
    projectId: 'tp1-firebase-28924',
    databaseURL: 'https://tp1-firebase-28924-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tp1-firebase-28924.appspot.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
